// Generated by CoffeeScript 1.6.3
var get;

get = require('../npm-packages');

exports.NPM = {
  success: function(test) {
    var err, fn;
    test.expect(1);
    fn = function(count) {
      test.equals(count, 0);
      return test.done();
    };
    err = function() {
      test.ok(false);
      return test.done();
    };
    return get('demo').then(fn, err);
  },
  error: function(test) {
    var fn;
    test.expect(1);
    fn = function() {
      test.ok(true);
      return test.done();
    };
    return get('ajkldanjkndjklfndjfnjkdsnfjrnfjkdndjkvnifsdvnfjkvnsrifrifnsermnerjifnerjfnjr').then((function() {}), fn, (function() {}));
  },
  progress: function(test) {
    var called, done, err, fn;
    test.expect(1);
    called = 0;
    fn = function() {
      return ++called;
    };
    done = function(total) {
      var expected;
      expected = Math.ceil(total / 100);
      test.equals(called, expected);
      return test.done();
    };
    err = function() {
      test.ok(false);
      return test.done();
    };
    return get('dominictarr').then(done, err, fn);
  }
};
